/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.niton.fileorganizer;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLaf;
import com.niton.fileorganizer.controller.MainController;
import com.niton.fileorganizer.gui.MainGui;
import com.niton.fileorganizer.gui.components.PathDisplay;
import com.niton.fileorganizer.model.OrganisationNode;

import javax.swing.*;
import java.io.*;

public class Launcher {

    public static File f = new File(System.getProperty("user.home"), "fileorder.dat");
    public static void main(String[] args) {


        MainController c;
        if(f.exists()){
            try(FileInputStream fis = new FileInputStream(f)) {
                ObjectInputStream ois = new ObjectInputStream(fis);
                c = (MainController) ois.readObject();
                c.reopenGui();
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null,"The savefile couldn't be read, sorry");
                c = new MainController();
                c.startApp();
            }
        }else {
            c = new MainController();
            c.startApp();
        }
        System.out.println(((OrganisationNode)c.guiController.getPathBuilderController().getModel().getRoot()).printTree());

    }
}
