/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.niton.fileorganizer;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLaf;
import com.niton.fileorganizer.controller.MainController;
import com.niton.fileorganizer.gui.MainGui;

public class Launcher {

    public static void main(String[] args) {
        MainController c = new MainController();
        c.startApp();
    }
}
